[[language]]
name = "go"
auto-format = true
formatter = { command = "goimports" }

[[language]]
name = "protobuf"
scope = "source.proto"
injection-regex = "protobuf"
file-types = ["proto"]
language-servers = [ "bufls", "pbkit" ]

[language-server]
bufls = { command = "bufls", args = ["serve"] }
pbkit = { command = "pb", args = [ "lsp" ] }
